site:
  title: nREPL
  url: https://nrepl.org/
  start_page: 1.3@nrepl::index.adoc
  keys:
    google_analytics: 'UA-128069102-1'
urls:
  latest_version_segment: latest
content:
  sources:
  - url: https://github.com/nrepl/nrepl.git
    branches: ['master']
    tags: ['1.0.0-antora', '1.1.0', 'v1.2.0-antora', 'v1.3.1-antora']
    start_path: doc
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    toc: ~
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: build/site
