site:
  title: nREPL
  url: https://nrepl.org/
  start_page: 0.6.0@nrepl::index.adoc
  keys:
    google_analytics: 'UA-128069102-1'
content:
  sources:
  - url: https://github.com/nrepl/nrepl.git
    branches: ['master']
    tags: ['0.5.3', '0.6.0']
    start_path: doc
asciidoc:
  attributes:
    linkattrs: ''
    toc: ~
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./docs
